package com.uandcode.effects.hilt

/**
 * Marks declarations that exist only to be used by code generated by the
 * Effects Hilt compiler. They are public for that reason alone and are not
 * part of the supported API surface.
 */
@Retention(AnnotationRetention.BINARY)
@Target(
    AnnotationTarget.CLASS,
    AnnotationTarget.FUNCTION,
    AnnotationTarget.PROPERTY,
)
@RequiresOptIn(
    level = RequiresOptIn.Level.ERROR,
    message = "Internal API of the Effects Hilt library. " +
        "It is used by generated code and must not be called directly.",
)
public annotation class InternalEffectsHiltApi
