import io.github.gradlenexus.publishplugin.NexusPublishExtension
import helpers.effectLibraryVersion
import helpers.loadLocalProperties

plugins {
    id("io.github.gradle-nexus.publish-plugin")
}

val localProperties = loadLocalProperties(rootProject)

configure<NexusPublishExtension> {
    repositories {
        sonatype {
            with(localProperties) {
                stagingProfileId = sonatypeStagingProfileId
                username = ossrhTokenUsername
                password = ossrhTokenPassword
                nexusUrl.set(uri("https://s01.oss.sonatype.org/service/local/"))
                snapshotRepositoryUrl.set(uri("https://s01.oss.sonatype.org/content/repositories/snapshots/"))
            }
        }
    }
}

// --- Maven Central Portal bundle ---------------------------------------------------------------
//
// Maven Central meters publishing by *file count* per calendar month, and every supporting file
// counts (signatures, checksums, sources/javadoc jars, POMs). To keep a release cheap we upload
// only what https://central.sonatype.org/publish/requirements/ actually requires:
//
//   * `.md5` and `.sha1` are mandatory, `.sha256`/`.sha512` are not
//     (suppressed at the source by systemProp.org.gradle.internal.publish.checksums.insecure)
//   * ".asc files don't need checksum files"
//   * maven-metadata.xml is generated by Central itself and does not belong in a Portal bundle

val catalogs = extensions.getByType<VersionCatalogsExtension>()
val localMavenRepoDir = layout.buildDirectory.dir("maven")

val cleanLocalMavenRepo = tasks.register<Delete>("cleanLocalMavenRepo") {
    description = "Removes artifacts staged by previous releases so they cannot leak into a bundle."
    group = "publishing"
    delete(localMavenRepoDir)
}

// Staging happens into a directory that cleanLocalMavenRepo wipes, so the publish tasks
// themselves - not just the aggregator below - have to be ordered after it.
subprojects {
    tasks.withType<PublishToMavenRepository>().configureEach {
        mustRunAfter(cleanLocalMavenRepo)
    }
}

val publishToLocalMavenRepo = tasks.register("publishToLocalMavenRepo") {
    description = "Stages every published module into the local build/maven repository."
    group = "publishing"
    dependsOn(provider {
        subprojects.flatMap { subproject ->
            subproject.tasks.withType(PublishToMavenRepository::class.java)
                .matching { it.repository?.name == "build" }
        }
    })
}

tasks.register<Zip>("centralBundle") {
    description = "Builds a Maven Central Portal deployment bundle containing only required files."
    group = "publishing"
    dependsOn(cleanLocalMavenRepo, publishToLocalMavenRepo)

    from(localMavenRepoDir)
    include("com/**")

    // Central generates its own repository metadata.
    exclude("**/maven-metadata.xml", "**/maven-metadata.xml.*")
    // Signatures do not need checksums of their own.
    exclude("**/*.asc.md5", "**/*.asc.sha1", "**/*.asc.sha256", "**/*.asc.sha512")
    // Belt and braces: optional checksums, in case the Gradle system property stops working.
    exclude("**/*.sha256", "**/*.sha512")

    archiveFileName = "central-bundle-${catalogs.effectLibraryVersion}.zip"
    destinationDirectory = layout.buildDirectory
}
