package com.elveum.effects.processor.data

import com.elveum.effects.processor.extensions.KSClassDeclarationWrapper
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.ksp.toClassName

class EffectMetadata(
    val targetInterfaceList: List<KSClassDeclarationWrapper>,
    val effectClassDeclaration: KSClassDeclarationWrapper,
    val hiltComponent: ClassName,
    val hiltScope: ClassName,
    val cleanUpMethodName: EffectCleanUpMethodName,
    val metadataDeclaration: KSClassDeclaration? = null,
) {

    val effectClassName: ClassName = effectClassDeclaration.toClassName()
    val dependencies: Dependencies by lazy { buildDependencies() }

    private val hiltComponentToConstNameMap = mapOf(
        Const.SingletonComponentName to Const.SingletonPriorityConstName,
        Const.ActivityRetainedComponentName to Const.ActivityRetainedPriorityConstName,
    )

    constructor(
        effectInfo: EffectInfo,
    ) : this(
        targetInterfaceList = effectInfo.targetInterfaceList,
        effectClassDeclaration = effectInfo.effectClassDeclaration,
        hiltComponent = effectInfo.hiltComponent,
        hiltScope = effectInfo.hiltScope,
        cleanUpMethodName = effectInfo.cleanUpMethodName,
    )

    fun shouldGenerateViewModelMediator(): Boolean {
        return hiltComponentToConstNameMap.keys.contains(hiltComponent)
    }

    fun getHiltComponentPriorityConstName(): String {
        return hiltComponentToConstNameMap[hiltComponent]
            ?: Const.OtherPriorityConstName
    }

    private fun buildDependencies(): Dependencies {
        return if (metadataDeclaration == null) {
            // input is located within the module being processed
            return Dependencies(
                aggregating = true,
                checkNotNull(effectClassDeclaration.containingFile)
            )
        } else {
            // inputs are read from metadata generated by other module
            Dependencies.ALL_FILES
        }
    }

}
